# Generated by Django 5.1.1 on 2024-09-27 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(upload_to='Media/Profile_Pic')),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('career_summary', models.TextField(max_length=500, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
