# Generated by Django 5.1.1 on 2024-09-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_institute_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute_model',
            old_name='state',
            new_name='division',
        ),
    ]
