# Generated by Django 5.1.1 on 2024-09-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_institute_model_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_model',
            name='degree_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education_model',
            name='end_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='education_model',
            name='field_of_study',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education_model',
            name='institute_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education_model',
            name='start_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='education_model',
            unique_together={('user', 'institute_name', 'degree_name')},
        ),
    ]
