# Generated by Django 5.1.1 on 2024-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_education_model_degree_name_education_model_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_of_Study_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
