# Generated by Django 5.1.1 on 2024-10-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_field_of_study_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreetype_model',
            name='degree_level',
            field=models.CharField(choices=[('ssc', 'SSC/Dakhil/Equivalent'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'Doctorate (PhD)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education_model',
            name='end_date',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='education_model',
            name='start_date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
