# Generated by Django 5.1.1 on 2024-10-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_degreetype_model_degree_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreetype_model',
            name='degree_level',
            field=models.CharField(choices=[('ssc', 'SSC/Dakhil/Equivalent'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'Doctorate (PhD)')], max_length=100, null=True),
        ),
    ]
