# Generated by Django 5.1.1 on 2024-09-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_state_institute_model_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_model',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
